name = "GNSSEphemeris"
uuid = "198fdfcd-e92c-4fb4-a40e-ea3ad0ac6fd5"
authors = ["Jakub Kaspar"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RinexRead = "2b0164f2-9e95-4962-8ceb-6e821dd993e7"
TimesDates = "bdfc003b-8df8-5c39-adcd-3a9087f5df4a"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[sources]
RinexRead = {url = "https://github.com/bukvoj/RinexRead.jl"}